#!/bin/sh
swayidle -w \
        
       timeout 5 'gtklock -d -c ~/.config/gtklock/config.css -b /home/rounak/Pictures/blue-mnt2.png' \
        
       timeout 10 'hyprctl dispatch dpms off' \
       
       after-resume 'hyprctl dispatch dpms on'
