#!/bin/sh
           swayidle -w \
                timeout 600 'gtklock -d -c ~/.config/gtklock/config.css -b /home/rounak/Pictures/blue-mnt2.png' \
                timeout 900 'hyprctl dispatch dpms off' 
